CREATE OR REPLACE TABLE MY_WORKSPACE.CLEANED_STG.DIM_AIRLINE AS 
SELECT distinct Operating_Airline, Operating_Airline_IATA_Code FROM CLEANED_AIRLINE_DATA;

CREATE OR REPLACE TABLE MY_WORKSPACE.CLEANED_STG.DIM_AIRCRAFT AS 
SELECT DISTINCT Aircraft_Model, Aircraft_Body_Type, Aircraft_Manufacturer FROM CLEANED_AIRLINE_DATA;

CREATE OR REPLACE TABLE MY_WORKSPACE.CLEANED_STG.DIM_REGION AS 
SELECT DISTINCT GEO_Summary, GEO_Region FROM CLEANED_AIRLINE_DATA;

CREATE OR REPLACE TABLE MY_WORKSPACE.CLEANED_STG.DIM_DATE AS 
SELECT DISTINCT 
    ACTIVITY_PERIOD_START_DATE AS FULL_DATE,
    YEAR(ACTIVITY_PERIOD_START_DATE) AS YEAR,
    MONTH(ACTIVITY_PERIOD_START_DATE) AS MONTH,
    DAY(ACTIVITY_PERIOD_START_DATE) AS DAY,
    DAYOFWEEK(ACTIVITY_PERIOD_START_DATE) AS WEEKDAY,
    QUARTER(ACTIVITY_PERIOD_START_DATE) AS QUARTER
FROM CLEANED_AIRLINE_DATA;


CREATE OR REPLACE TABLE MY_WORKSPACE.CLEANED_STG.FACT_AIRLINE_TRAFFIC AS
SELECT 
    a.Operating_Airline,
    a.Operating_Airline_IATA_Code,
    b.Aircraft_Model,
    b.Aircraft_Body_Type,
    b.Aircraft_Manufacturer,
    c.GEO_Summary,
    c.GEO_Region,
    d.Activity_Period,
    d.Activity_Period_Start_Date,
    d.Landing_Count,
    d.Total_Landed_Weight
FROM MY_WORKSPACE.CLEANED_STG.CLEANED_AIRLINE_DATA d
LEFT JOIN MY_WORKSPACE.CLEANED_STG.DIM_AIRLINE a 
    ON d.Operating_Airline = a.Operating_Airline 
    AND d.Operating_Airline_IATA_Code = a.Operating_Airline_IATA_Code
LEFT JOIN MY_WORKSPACE.CLEANED_STG.DIM_AIRCRAFT b 
    ON d.Aircraft_Model = b.Aircraft_Model 
    AND d.Aircraft_Body_Type = b.Aircraft_Body_Type 
    AND d.Aircraft_Manufacturer = b.Aircraft_Manufacturer
LEFT JOIN MY_WORKSPACE.CLEANED_STG.DIM_REGION c 
    ON d.GEO_Summary = c.GEO_Summary 
    AND d.GEO_Region = c.GEO_Region;


select * from MY_WORKSPACE.CLEANED_STG.FACT_AIRLINE_TRAFFIC
    
